# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: andythewhale
email: andymiller1313@gmail.com
description: I'm andy, this is my blog. I'm a biochemical engineer, programmer, and athlete. I'll use this blog to talk about programming stuff I'm working on, critiquing books/movies/shows, and otther random things. 
baseurl: "andythewhale/github.io" # the subpath of your site, e.g. /blog
url: "https://andythewhale/github.io" # the base hostname & protocol for your site
twitter_username: andythewhale
github_username:  andythewhale

# Build settings
markdown: kramdown
future: true
timezone: TIMEZONE